### ISSUE TITLE
BUG: Plank overriding user set options

### ISSUE THREAD

**Issue by ajstrongdev** [rhino-linux/unicorn#20]
Fix plank automatically overriding the user-set options for it within the Unicorn Desktop

**Comment by oklopfer** [comment]
I think we may have to pick a new dock entirely to actually fix this. setting as rollover.

**Comment by TActually** [comment]
Ya know, You're not doing anything with Plank that can't be done with a standard XFCE panel.
Especially since you're not using the parabolic effect.
The only thing that would not be as "cool" would be the ease of adding and removing applications from the panel and.. no rounded corners.

**Comment by oklopfer** [comment]
Solved with latest merges lesgoooooo

**Comment by Udayendu** [comment]
@oklopfer I am also facing the same issue. How you solved it ? I am using 2023.2-RC.

**Comment by Udayendu** [comment]
I found the patch https://github.com/rhino-linux/unicorn/pull/18/commits/9a3dd59ab993c8524c06bd615e0e6df907362830#diff-e38a1832cec98140882f2255cc852cbcee5aaab721620fecb1e6e860d87f49d5 and applied it using `nala update && nala upgrade -y` but still it didn't work. And the reason was, when I changed the dock position from left to bottom and icon size from 48 to 30, it was not getting applied into the file. So I had to manually change in the file and things are working now as expected.

I found that the file `docks.ini` was owned by root but I was making the changes as a normal user. So may be it was not allowing to update the file as a normal user. Hence please check when we are copying this file to user's .config location, are we also changing the ownership to $USER. Because under `.config` in `/home/$USER` all the files are owner by `$USER` except this file.

**Comment by oklopfer** [comment]
Why are you using nala to update Pacstall packages? 

Yes, you need to edit docks.ini, and it does not need to be owned by the user. It exists because Plank does not provide ordering to the dock correctly, so we override that. The fix here was with Plank Dock updates overriding user settings, not with Plank Dock overriding in general. As long as we use Plank, it will always be the strongly recommended method to edit the docks.ini file, so that Plank works properly, rather than trying to edit plank config by GUI.

**Comment by oklopfer** [comment]
Changed ownership on docks here https://github.com/pacstall/pacstall-programs/commit/4a694a29723e46bc904ab128cd72e7fe79401c69. Please use `rpk update`, not nala.
